services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:6.0
    container_name: mongodbgateway
    restart: always
    ports:
      - "27099:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: IdentityProviderGateway
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge